version: 2

sources:
  - name: default
    database: workspace
    schema: default
    tables: 
      - name: fact_sales
      - name: fact_returns
      - name: dim_date
      - name: dim_store
      - name: dim_product
      - name: dim_customer
